# Introdução do tratamento de dados: 

1. Importar as bibliotecas necessárias; 
2. Fazer o primeiro tratamento dos dados nececssários;
3. Primeira exposição de dados referente as idades dos pilotos de F1 atuais.

# 1- Importando as bibliotecas:

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime 

import seaborn as sns

In [26]:
drivers = pd.read_csv('drivers.csv') 
results = pd.read_csv('results.csv')  
season = pd.read_csv('seasons.csv') 
races = pd.read_csv('races.csv')
driver_standing = pd.read_csv('driver_standings.csv')

In [9]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [11]:
drivers.columns

Index(['driverId', 'driverRef', 'number', 'code', 'forename', 'surname', 'dob',
       'nationality', 'url'],
      dtype='object')

In [16]:
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [17]:
results.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId'],
      dtype='object')

In [20]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [21]:
races.columns

Index(['raceId', 'year', 'round', 'circuitId', 'name', 'date', 'time', 'url',
       'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time',
       'quali_date', 'quali_time', 'sprint_date', 'sprint_time'],
      dtype='object')

# Definindo os dados necessários para a análise de idades dos pilotos: 

## Merge em um único dataset para melhor visualização

In [34]:
data = pd.merge(results,races[['raceId','year','name','round','date']],on = 'raceId',how = 'left')
data =pd.merge(data,drivers[['driverId','driverRef','forename','surname','nationality','dob']],on='driverId',how='left')

In [35]:
data

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,statusId,year,name,round,date,driverRef,forename,surname,nationality,dob
0,1,18,1,1,22,1,1,1,1,10.0,...,1,2008,Australian Grand Prix,1,2008-03-16,hamilton,Lewis,Hamilton,British,1985-01-07
1,2,18,2,2,3,5,2,2,2,8.0,...,1,2008,Australian Grand Prix,1,2008-03-16,heidfeld,Nick,Heidfeld,German,1977-05-10
2,3,18,3,3,7,7,3,3,3,6.0,...,1,2008,Australian Grand Prix,1,2008-03-16,rosberg,Nico,Rosberg,German,1985-06-27
3,4,18,4,4,5,11,4,4,4,5.0,...,1,2008,Australian Grand Prix,1,2008-03-16,alonso,Fernando,Alonso,Spanish,1981-07-29
4,5,18,5,1,23,3,5,5,5,4.0,...,1,2008,Australian Grand Prix,1,2008-03-16,kovalainen,Heikki,Kovalainen,Finnish,1981-10-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26075,26081,1110,817,213,3,19,16,16,16,0.0,...,1,2023,Belgian Grand Prix,12,2023-07-30,ricciardo,Daniel,Ricciardo,Australian,1989-07-01
26076,26082,1110,858,3,2,18,17,17,17,0.0,...,1,2023,Belgian Grand Prix,12,2023-07-30,sargeant,Logan,Sargeant,American,2000-12-31
26077,26083,1110,807,210,27,0,18,18,18,0.0,...,1,2023,Belgian Grand Prix,12,2023-07-30,hulkenberg,Nico,Hülkenberg,German,1987-08-19
26078,26084,1110,832,6,55,4,\N,R,19,0.0,...,130,2023,Belgian Grand Prix,12,2023-07-30,sainz,Carlos,Sainz,Spanish,1994-09-01
26079,26085,1110,857,1,81,5,\N,R,20,0.0,...,130,2023,Belgian Grand Prix,12,2023-07-30,piastri,Oscar,Piastri,Australian,2001-04-06

In [36]:
data.drop(['resultId', 'raceId', 'constructorId', 'number','position','positionText','statusId','driverId', 'points', 'grid','positionOrder' ],axis =1,inplace = True)

In [37]:
data

,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,year,name,round,date,driverRef,forename,surname,nationality,dob
0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,2008,Australian Grand Prix,1,2008-03-16,hamilton,Lewis,Hamilton,British,1985-01-07
1,58,+5.478,5696094,41,3,1:27.739,217.586,2008,Australian Grand Prix,1,2008-03-16,heidfeld,Nick,Heidfeld,German,1977-05-10
2,58,+8.163,5698779,41,5,1:28.090,216.719,2008,Australian Grand Prix,1,2008-03-16,rosberg,Nico,Rosberg,German,1985-06-27
3,58,+17.181,5707797,58,7,1:28.603,215.464,2008,Australian Grand Prix,1,2008-03-16,alonso,Fernando,Alonso,Spanish,1981-07-29
4,58,+18.014,5708630,43,1,1:27.418,218.385,2008,Australian Grand Prix,1,2008-03-16,kovalainen,Heikki,Kovalainen,Finnish,1981-10-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26075,44,+1:43.071,5053521,25,15,1:50.994,227.169,2023,Belgian Grand Prix,12,2023-07-30,ricciardo,Daniel,Ricciardo,Australian,1989-07-01
26076,44,+1:44.476,5054926,37,9,1:50.486,228.213,2023,Belgian Grand Prix,12,2023-07-30,sargeant,Logan,Sargeant,American,2000-12-31
26077,44,+1:50.450,5060900,26,4,1:49.907,229.415,2023,Belgian Grand Prix,12,2023-07-30,hulkenberg,Nico,Hülkenberg,German,1987-08-19
26078,23,\N,\N,9,19,1:53.138,222.864,2023,Belgian Grand Prix,12,2023-07-30,sainz,Carlos,Sainz,Spanish,1994-09-01
26079,0,\N,\N,\N,0,\N,\N,2023,Belgian Grand Prix,12,2023-07-30,piastri,Oscar,Piastri,Australian,2001-04-06